stages:
  train_mlp:
    cmd: PYTHONPATH=. python ddpm.py --config configs/sps/mlp.json
    deps:
    - static
    - configs/sps/mlp.json # todo move to param
    outs:
    - exps/mlp/model.pth
  train_mlp_sps_from_scratch:
    cmd: PYTHONPATH=. python ddpm.py --config configs/sps/mlp_sps_from_scratch.json
    deps:
    - static
    - configs/sps/mlp_sps_from_scratch.json # todo move to param
  train_mlp_sps_from_pretrained:
    cmd: PYTHONPATH=. python ddpm.py --config configs/sps/mlp_sps_from_pretrained.json
    deps:
    - static
    - configs/sps/mlp_sps_from_pretrained.json # todo move to param
    - exps/mlp/model.pth # todo move to params and to config template


  pd_mlp_pretrain_128:
    cmd: PYTHONPATH=. python ddpm.py --config configs/progressive_distillation/mlp_pretrain_128.json
    deps:
    - static
    - configs/progressive_distillation/mlp_pretrain_128.json # todo move to param
    outs:
    - exps/mlp_pretrain_128/model.pth

  pd_no_beta_correction:
    cmd: PYTHONPATH=. python progressive_distillation.py --config configs/progressive_distillation/no_beta_correction.json
    deps:
    - static
    - configs/progressive_distillation/no_beta_correction.json # todo move to param
    - exps/mlp_pretrain_128/model.pth

  pd_multistage:
    cmd: PYTHONPATH=. python progressive_distillation.py --config configs/progressive_distillation/multistage.json
    deps:
    - progressive_distillation.py
    - static
    - configs/progressive_distillation/multistage.json # todo move to param
    - exps/mlp_pretrain_128/model.pth

  pd_multistage_sps:
    cmd: PYTHONPATH=. python progressive_distillation.py --config configs/progressive_distillation/multistage_sps.json
    deps:
    - progressive_distillation.py
    - static
    - configs/progressive_distillation/multistage_sps.json # todo move to param
    - exps/mlp_pretrain_128/model.pth
